// <auto-generated />
using System;
using BeerOverflow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeerOverflow.Data.Migrations
{
    [DbContext(typeof(BeerOverflowContext))]
    [Migration("20200425122351_addedSeeder")]
    partial class addedSeeder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BeerOverflow.Data.Entities.Beer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AlcByVol")
                        .HasColumnType("float");

                    b.Property<string>("BeerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<int>("BeerTypeId")
                        .HasColumnType("int");

                    b.Property<int>("BreweryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateUnlisted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BeerName")
                        .IsUnique();

                    b.HasIndex("BeerTypeId");

                    b.HasIndex("BreweryId");

                    b.ToTable("Beers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlcByVol = 5.5999999999999996,
                            BeerName = "Possession Porter",
                            BeerTypeId = 1,
                            BreweryId = 1,
                            Description = "American beer"
                        },
                        new
                        {
                            Id = 2,
                            AlcByVol = 5.0,
                            BeerName = "Wexford Irish Cream Ale",
                            BeerTypeId = 3,
                            BreweryId = 3,
                            Description = "English beer"
                        },
                        new
                        {
                            Id = 3,
                            AlcByVol = 4.9000000000000004,
                            BeerName = "Hoegaarden",
                            BeerTypeId = 3,
                            BreweryId = 5,
                            Description = "Belge beer"
                        },
                        new
                        {
                            Id = 4,
                            AlcByVol = 5.0,
                            BeerName = "Heineken",
                            BeerTypeId = 3,
                            BreweryId = 4,
                            Description = "Dutch beer"
                        },
                        new
                        {
                            Id = 5,
                            AlcByVol = 4.5,
                            BeerName = "Corona Extra",
                            BeerTypeId = 2,
                            BreweryId = 6,
                            Description = "Mexican-Belge beer"
                        },
                        new
                        {
                            Id = 6,
                            AlcByVol = 4.0,
                            BeerName = "Snow",
                            BeerTypeId = 2,
                            BreweryId = 7,
                            Description = "Chinese beer"
                        },
                        new
                        {
                            Id = 7,
                            AlcByVol = 5.0,
                            BeerName = "Budweiser",
                            BeerTypeId = 2,
                            BreweryId = 1,
                            Description = "American beer"
                        },
                        new
                        {
                            Id = 8,
                            AlcByVol = 5.0,
                            BeerName = "Left Hand Milk Stout",
                            BeerTypeId = 4,
                            BreweryId = 8,
                            Description = "English beer"
                        },
                        new
                        {
                            Id = 9,
                            AlcByVol = 5.0,
                            BeerName = "Tsingtao",
                            BeerTypeId = 3,
                            BreweryId = 3,
                            Description = "Chinese beer"
                        },
                        new
                        {
                            Id = 10,
                            AlcByVol = 4.2000000000000002,
                            BeerName = "Coors Light",
                            BeerTypeId = 2,
                            BreweryId = 10,
                            Description = "English beer"
                        });
                });

            modelBuilder.Entity("BeerOverflow.Data.Entities.BeerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("BeerTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Style of beer that was developed in London in the early eighteenth century.",
                            Type = "Porter"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Type of beer conditioned at low temperatures.",
                            Type = "Lager"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Type of beer brewed using a warm fermentation method",
                            Type = "Ale"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Dark, top-fermented beer with a number of variations, including dry stout, Baltic porter, milk stout, and imperial stout.",
                            Type = "Stout"
                        });
                });

            modelBuilder.Entity("BeerOverflow.Data.Entities.Brewery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Breweries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Description = "America",
                            Name = "Diamond Knot Brewery"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Description = "American brewery",
                            Name = "Anheuser-Busch"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 4,
                            Description = "English brewery",
                            Name = "Greene King"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 3,
                            Description = "Dutch brewery",
                            Name = "Heineken International"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 2,
                            Description = "Belge brewery",
                            Name = "Brouwerij van Hoegaarden"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 7,
                            Description = "Mexican brewery",
                            Name = "Grupo Modelo"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 9,
                            Description = "Chinese brewery",
                            Name = "CR Snow"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 1,
                            Description = "American brewery",
                            Name = "Left Hand Brewing"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 4,
                            Description = "Chinese brewery",
                            Name = "Tsingtao Brewery"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 1,
                            Description = "American brewery",
                            Name = "Coors Brewing Company"
                        });
                });

            modelBuilder.Entity("BeerOverflow.Data.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 4,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 9,
                            Name = "China"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Norway"
                        });
                });

            modelBuilder.Entity("BeerOverflow.Data.Entities.RateReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsInapropriate")
                        .HasColumnType("bit");

                    b.Property<int>("LikeReview")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.HasIndex("UserId");

                    b.ToTable("RateReviews");
                });

            modelBuilder.Entity("BeerOverflow.Data.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BeerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("RMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.HasIndex("UserId", "BeerId")
                        .IsUnique();

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeerId = 1,
                            RMessage = "Cool beer!",
                            Rating = 5,
                            ReviewedOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(3726),
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            BeerId = 7,
                            RMessage = "Very fresh, would buy again!",
                            Rating = 4,
                            ReviewedOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(4743),
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            BeerId = 8,
                            RMessage = "I don't recommend it!",
                            Rating = 1,
                            ReviewedOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(4788),
                            UserId = 6
                        },
                        new
                        {
                            Id = 4,
                            BeerId = 8,
                            RMessage = "Top class!",
                            Rating = 5,
                            ReviewedOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(4811),
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            BeerId = 2,
                            RMessage = "Not great, not terrible.",
                            Rating = 3,
                            ReviewedOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(4831),
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            BeerId = 5,
                            RMessage = "Not my taste.",
                            Rating = 2,
                            ReviewedOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(4854),
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            BeerId = 2,
                            RMessage = "Rip off!",
                            Rating = 1,
                            ReviewedOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(4874),
                            UserId = 4
                        },
                        new
                        {
                            Id = 8,
                            BeerId = 4,
                            RMessage = "I already bought another 10 of those!",
                            Rating = 5,
                            ReviewedOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(4957),
                            UserId = 6
                        },
                        new
                        {
                            Id = 9,
                            BeerId = 3,
                            RMessage = "Decent taste and price!",
                            Rating = 4,
                            ReviewedOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(4981),
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            BeerId = 10,
                            RMessage = "My friend lied to me, its not that good.",
                            Rating = 3,
                            ReviewedOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(5003),
                            UserId = 3
                        },
                        new
                        {
                            Id = 11,
                            BeerId = 7,
                            RMessage = "Excellent!",
                            Rating = 5,
                            ReviewedOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(5023),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BeerOverflow.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BeerOverflow.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2020, 4, 25, 12, 23, 50, 554, DateTimeKind.Utc).AddTicks(9464),
                            Email = "bvuchev@abv.bg",
                            FirstName = "Boyan",
                            LastName = "Vuchev",
                            Username = "Boyanski"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(357),
                            Email = "rsimeonovv@abv.bg",
                            FirstName = "Radoslav",
                            LastName = "Simeonov",
                            Username = "RSimeonov"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(401),
                            Email = "peshop@gmail.com",
                            FirstName = "Petur",
                            LastName = "Petrov",
                            Username = "PeturPetrof"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(424),
                            Email = "vankatas@gmail.com",
                            FirstName = "Ivan",
                            LastName = "Stoyanov",
                            Username = "VankataV"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(444),
                            Email = "geriflow@gmail.com",
                            FirstName = "Gergana",
                            LastName = "Ivanova",
                            Username = "GeritoIv"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(467),
                            Email = "mimiang@gmail.com",
                            FirstName = "Mariya",
                            LastName = "Angelova",
                            Username = "MimiG"
                        });
                });

            modelBuilder.Entity("BeerOverflow.Data.Entities.UserBeers", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("BeerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DrankOn")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "BeerId");

                    b.HasIndex("BeerId");

                    b.ToTable("UserBeers");

                    b.HasData(
                        new
                        {
                            UserId = 2,
                            BeerId = 7,
                            DrankOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(6737)
                        },
                        new
                        {
                            UserId = 3,
                            BeerId = 7,
                            DrankOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(7618)
                        },
                        new
                        {
                            UserId = 3,
                            BeerId = 5
                        },
                        new
                        {
                            UserId = 3,
                            BeerId = 10
                        },
                        new
                        {
                            UserId = 1,
                            BeerId = 3,
                            DrankOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(7699)
                        },
                        new
                        {
                            UserId = 4,
                            BeerId = 2,
                            DrankOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(7722)
                        },
                        new
                        {
                            UserId = 4,
                            BeerId = 1,
                            DrankOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(7742)
                        },
                        new
                        {
                            UserId = 4,
                            BeerId = 5,
                            DrankOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(7762)
                        },
                        new
                        {
                            UserId = 6,
                            BeerId = 1
                        },
                        new
                        {
                            UserId = 6,
                            BeerId = 3
                        },
                        new
                        {
                            UserId = 6,
                            BeerId = 4
                        },
                        new
                        {
                            UserId = 2,
                            BeerId = 1
                        },
                        new
                        {
                            UserId = 2,
                            BeerId = 4
                        },
                        new
                        {
                            UserId = 3,
                            BeerId = 3
                        },
                        new
                        {
                            UserId = 4,
                            BeerId = 7
                        },
                        new
                        {
                            UserId = 5,
                            BeerId = 8,
                            DrankOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(7909)
                        },
                        new
                        {
                            UserId = 6,
                            BeerId = 8,
                            DrankOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(7928)
                        },
                        new
                        {
                            UserId = 1,
                            BeerId = 2,
                            DrankOn = new DateTime(2020, 4, 25, 12, 23, 50, 555, DateTimeKind.Utc).AddTicks(7949)
                        });
                });

            modelBuilder.Entity("BeerOverflow.Data.Entities.UserRoles", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("BeerOverflow.Data.Entities.Beer", b =>
                {
                    b.HasOne("BeerOverflow.Data.Entities.BeerType", "BeerType")
                        .WithMany("Beers")
                        .HasForeignKey("BeerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerOverflow.Data.Entities.Brewery", "Brewery")
                        .WithMany("Beers")
                        .HasForeignKey("BreweryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeerOverflow.Data.Entities.Brewery", b =>
                {
                    b.HasOne("BeerOverflow.Data.Entities.Country", "Country")
                        .WithMany("Breweries")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeerOverflow.Data.Entities.RateReview", b =>
                {
                    b.HasOne("BeerOverflow.Data.Entities.Review", "Review")
                        .WithMany("RateReviews")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerOverflow.Data.Entities.User", "User")
                        .WithMany("RateReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BeerOverflow.Data.Entities.Review", b =>
                {
                    b.HasOne("BeerOverflow.Data.Entities.Beer", "Beer")
                        .WithMany("Reviews")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerOverflow.Data.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeerOverflow.Data.Entities.UserBeers", b =>
                {
                    b.HasOne("BeerOverflow.Data.Entities.Beer", "Beer")
                        .WithMany()
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerOverflow.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeerOverflow.Data.Entities.UserRoles", b =>
                {
                    b.HasOne("BeerOverflow.Data.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerOverflow.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
